### ISSUE TITLE
Fan mode in Homekit

### ISSUE THREAD

**Issue by systemx-xx** [jnimmo/hass-intesisbox#27]
I know this is a  long shot but ive dug through the source and I am not familiar with HomeAssitant enough yet to work out what I am doing but I am struggling to get the fan speeds across into Homekit. It works  fine in HomeAssistant and ive pushed the climate. entity to HomeKit, however I only get Mode/Temp control in HomeKit. There is no fan entity that I can see to expose but I am not entirely sure internally how this works.

**Comment by jbergler** [comment]
I've found a lead! The homekit integration [looks](https://github.com/home-assistant/core/blob/dev/homeassistant/components/homekit/type_thermostats.py#L287) like it only exposes fan modes if they match strings like 'low', 'medium', 'high', while we're exposing 1, 2, 3

I'll see what I can do!

**Comment by jbergler** [comment]
@systemx-xx I'm going to hold off merging the above PR until I hear from @jnimmo since it's a breaking change.

You can install the component from my fork in the meantime if you'd like to try it out.
I found I had to call the reset accessory service on the climate entity in HA for the Home app on my phone to see the change.
